import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
import ReactQueryProvider from "./providers/queryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <GoogleOAuthProvider clientId="939540789758-tl6e37h6an0grjn2dmpa2j10a4rbldmf.apps.googleusercontent.com">
            <div>
              <Toaster />
            </div>
            {children}
          </GoogleOAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
